import { useMemo, useState } from "react";
import type { ProgressMap, Question } from "../types";
import type { StudyState } from "../study/types";
import { SourceImage } from "../components/SourceImage";
import { browseQuestions, ERROR_TAGS, findQuestions, parseQuestionIds, similarQuestions, type BrowserFilters, type ErrorTag, type ProductivityState } from "./productivity";
import "./productivity.css";

export function ProductivityPanel({ questions, progress, study, state, onChange, onPractice, onBack }: { questions: Question[]; progress: ProgressMap; study: StudyState | null; state: ProductivityState; onChange: (state: ProductivityState) => void; onPractice: (ids: string[]) => void; onBack: () => void }) {
  const [tab, setTab] = useState<"finder"|"browser"|"queue"|"errors">("finder");
  const [query, setQuery] = useState(""); const [ids, setIds] = useState(""); const [selected, setSelected] = useState<Question|null>(null);
  const [page, setPage] = useState(0);
  const [errorSubject,setErrorSubject]=useState("All"),[errorTag,setErrorTag]=useState("All");
  const [filters, setFilters] = useState<BrowserFilters>({ query:"", test:"All", domain:"", skill:"", difficulty:"All", history:"all" });
  const parsed = useMemo(()=>parseQuestionIds(ids, questions),[ids,questions]);
  const results = useMemo(()=>findQuestions(questions,query),[questions,query]);
  const browsed = useMemo(()=>browseQuestions(questions,progress,filters),[questions,progress,filters]);
  const queue = state.queue.map(id=>questions.find(q=>q.id===id)).filter(Boolean) as Question[];
  const setQueue = (queue: string[]) => onChange({...state,queue:[...new Set(queue)]});
  const tag = (id:string, tags:ErrorTag[]) => { const errors={...state.errors}; if(tags.length)errors[id]={tags,updatedAt:new Date().toISOString()};else delete errors[id];onChange({...state,errors}); };
  const errors = questions.filter(q=>progress[q.id]?.incorrectAttempts).sort((a,b)=>(Date.parse(progress[b.id]?.lastAttemptDate??"")||0)-(Date.parse(progress[a.id]?.lastAttemptDate??"")||0));
  const filteredErrors=errors.filter(q=>(errorSubject==="All"||q.test===errorSubject)&&(errorTag==="All"||(state.errors[q.id]?.tags??[]).includes(errorTag as ErrorTag)));
  if(selected) return <StudyQuestion question={selected} progress={progress} study={study} tags={state.errors[selected.id]?.tags??[]} queued={state.queue.includes(selected.id)} onBack={()=>setSelected(null)} onPractice={()=>onPractice([selected.id])} onQueue={()=>setQueue(state.queue.includes(selected.id)?state.queue.filter(id=>id!==selected.id):[...state.queue,selected.id])} onSimilar={()=>onPractice(similarQuestions(selected,questions,progress).map(q=>q.id))} />;
  const domains=[...new Set(questions.filter(q=>filters.test==="All"||q.test===filters.test).map(q=>q.domain))].sort();
  const skills=[...new Set(questions.filter(q=>(!filters.domain||q.domain===filters.domain)&&(filters.test==="All"||q.test===filters.test)).map(q=>q.skill))].sort();
  return <main className="page productivity"><button className="text-button back" onClick={onBack}>← Home</button><p className="eyebrow">QUESTION TOOLS</p><h1>Find, organize, and review</h1>
    <nav className="productivity-tabs">{(["finder","browser","queue","errors"] as const).map(value=><button key={value} className={tab===value?"selected":""} onClick={()=>{setTab(value);setPage(0)}}>{value==="errors"?"Error Notebook":value[0].toUpperCase()+value.slice(1)}{value==="queue"?` (${queue.length})`:""}</button>)}</nav>
    {tab==="finder"&&<><section className="tool-card"><h2>Question Finder</h2><input aria-label="Find question" placeholder="Exact or partial ID, or question text" value={query} onChange={e=>setQuery(e.target.value)}/><QuestionRows questions={results} onOpen={setSelected}/></section>
      <section className="tool-card"><h2>Create set from IDs</h2><textarea aria-label="Question IDs" rows={5} placeholder="Paste IDs separated by spaces, commas, or lines" value={ids} onChange={e=>setIds(e.target.value)}/><p>{parsed.ids.length} valid · {parsed.duplicate.length} duplicates ignored</p>{parsed.invalid.length>0&&<p className="error-list">Invalid: {parsed.invalid.join(", ")}</p>}<button className="primary" disabled={!parsed.ids.length} onClick={()=>onPractice(parsed.ids)}>Practice this set</button></section></>}
    {tab==="browser"&&<section className="tool-card"><h2>Question Browser</h2><div className="browser-filters"><input aria-label="Browser search" placeholder="ID or text" value={filters.query} onChange={e=>{setFilters({...filters,query:e.target.value});setPage(0)}}/><select aria-label="Browser subject" value={filters.test} onChange={e=>setFilters({...filters,test:e.target.value as BrowserFilters["test"],domain:"",skill:""})}><option>All</option><option>Math</option><option>Reading and Writing</option></select><select aria-label="Browser domain" value={filters.domain} onChange={e=>setFilters({...filters,domain:e.target.value,skill:""})}><option value="">All domains</option>{domains.map(v=><option key={v}>{v}</option>)}</select><select aria-label="Browser skill" value={filters.skill} onChange={e=>setFilters({...filters,skill:e.target.value})}><option value="">All skills</option>{skills.map(v=><option key={v}>{v}</option>)}</select><select aria-label="Browser difficulty" value={filters.difficulty} onChange={e=>setFilters({...filters,difficulty:e.target.value as BrowserFilters["difficulty"]})}><option>All</option><option>Easy</option><option>Medium</option><option>Hard</option></select><select aria-label="Browser history" value={filters.history} onChange={e=>setFilters({...filters,history:e.target.value as BrowserFilters["history"]})}><option value="all">All history</option><option value="unseen">Unseen</option><option value="seen">Seen</option><option value="correct">Correct</option><option value="incorrect">Incorrect</option><option value="bookmarked">Bookmarked</option></select></div><p>{browsed.length.toLocaleString()} matching questions</p><QuestionRows questions={browsed.slice(page*50,page*50+50)} onOpen={setSelected}/><div className="button-row"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(browsed.length/50))}</span><button disabled={(page+1)*50>=browsed.length} onClick={()=>setPage(page+1)}>Next</button></div></section>}
    {tab==="queue"&&<section className="tool-card"><h2>Study Queue</h2><div className="button-row"><button className="primary" disabled={!queue.length} onClick={()=>onPractice(state.queue)}>Start Queue</button><button disabled={!queue.length} onClick={()=>setQueue([])}>Clear queue</button></div>{queue.map(q=><div className="queue-row" key={q.id}><button className="text-button" onClick={()=>setSelected(q)}><strong>{q.questionId}</strong> · {q.skill}</button><button onClick={()=>setQueue(state.queue.filter(id=>id!==q.id))}>Remove</button></div>)}{!queue.length&&<p className="muted">Your queue is empty.</p>}</section>}
    {tab==="errors"&&<section className="tool-card"><h2>Error Notebook</h2><p>{filteredErrors.length} shown · {errors.length} questions missed · tags are optional</p><div className="button-row"><select aria-label="Error subject" value={errorSubject} onChange={e=>setErrorSubject(e.target.value)}><option>All</option><option>Math</option><option>Reading and Writing</option></select><select aria-label="Error tag" value={errorTag} onChange={e=>setErrorTag(e.target.value)}><option>All</option>{ERROR_TAGS.map(value=><option key={value}>{value}</option>)}</select></div>{filteredErrors.slice(0,100).map(q=>{const p=progress[q.id], chosen=state.errors[q.id]?.tags??[];return <article className="error-entry" key={q.id}><button className="text-button" onClick={()=>setSelected(q)}><strong>{q.questionId}</strong> · {q.test} · {q.domain} · {q.skill}</button><small>{p.lastAttemptDate?new Date(p.lastAttemptDate).toLocaleDateString():"Date unavailable"}{p.notes?` · Note: ${p.notes}`:""}{p.bookmark?" · Bookmarked":""}</small><div className="tag-row">{ERROR_TAGS.map(value=><button key={value} aria-pressed={chosen.includes(value)} className={chosen.includes(value)?"selected":""} onClick={()=>tag(q.id,chosen.includes(value)?chosen.filter(t=>t!==value):[...chosen,value])}>{value}</button>)}</div></article>})}</section>}
  </main>;
}

function QuestionRows({questions,onOpen}:{questions:Question[];onOpen:(q:Question)=>void}) { return <div className="finder-results">{questions.map(q=><button key={q.id} onClick={()=>onOpen(q)}><strong>{q.questionId}</strong><span>{q.test} · {q.domain} · {q.skill} · {q.difficulty}</span><small>{(q.stem||q.passage).slice(0,150)}</small></button>)}</div> }

function StudyQuestion({question:q,progress,study,tags,queued,onBack,onPractice,onQueue,onSimilar}:{question:Question;progress:ProgressMap;study:StudyState|null;tags:ErrorTag[];queued:boolean;onBack:()=>void;onPractice:()=>void;onQueue:()=>void;onSimilar:()=>void}) {
  const [answer,setAnswer]=useState(false), p=progress[q.id], evidence=study?.evidence[q.id]??[];
  return <main className="page study-view"><button className="text-button back" onClick={onBack}>← Results</button><p className="eyebrow">STUDY / VIEW · NO PROGRESS RECORDED</p><h1>{q.questionId}</h1><p>{q.test} · {q.domain} · {q.skill} · {q.difficulty}</p>{q.passage&&<div className="study-passage">{q.passage}</div>}{q.passageAssets?.map(a=><SourceImage key={a} src={a} alt="Passage visual" dpi={q.assetDpi}/>) }<div className="question-text">{q.assets.length?q.assets.map(a=><SourceImage key={a} src={a} alt={`Question ${q.questionId}`} dpi={q.assetDpi}/>):q.stem}</div>{q.choices.map(c=><div className="study-choice" key={c.label}><strong>{c.label}</strong> {c.assets?.length?c.assets.map(a=><SourceImage key={a} src={a} alt={`Choice ${c.label}`} dpi={q.assetDpi}/>):c.text}</div>)}<div className="button-row"><button className="primary" onClick={onPractice}>Practice this question</button><button onClick={onSimilar}>Practice similar questions</button><button onClick={onQueue}>{queued?"Remove from Study Queue":"Add to Study Queue"}</button><button onClick={()=>setAnswer(!answer)}>{answer?"Hide answer":"Show answer and explanation"}</button></div>{answer&&<section className="answer-review"><h2>Correct answer: {q.correctAnswer}</h2><p>{q.rationale}</p>{q.rationaleAssets.map(a=><SourceImage key={a} src={a} alt="Explanation" dpi={q.assetDpi}/>)}</section>}<section className="question-history"><h2>Question history</h2><p>First seen: {evidence[0]?.at?new Date(evidence[0].at).toLocaleString():"Unavailable"}</p><p>Last seen: {p?.lastAttemptDate?new Date(p.lastAttemptDate).toLocaleString():"Never"}</p><p>Attempts: {p?.attempts??0}{evidence.length?` · ${evidence.map(e=>e.correct?"✅":"❌").join(" ")}`:""}</p><p>Notes: {p?.notes||"None"} · Bookmark: {p?.bookmark?"Yes":"No"}</p><p>Error tags: {tags.join(", ")||"None"}</p></section></main>;
}
